name: sales_insight_mate
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.1.9
  excel: ^4.0.6
  intl: ^0.20.2
  fl_chart: ^0.70.2
  provider: ^6.1.2

flutter:
  uses-material-design: true
